services:
  postgres:
    image: postgres:17
    environment:
      - POSTGRES_USER=test-user
      - POSTGRES_PASSWORD=test-pw
      - POSTGRES_DB=finance_tracker_db
    ports:
      - 6501:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/
volumes:
  postgres_data:
