services:
  postgres:
    image: postgres:17
    environment:
      - POSTGRES_USER=test-user
      - POSTGRES_PASSWORD=test-pw
      - POSTGRES_DB=finance_tracker_db
    ports:
      - 6501:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - ./docker-entrypoint-initdb.d/:/docker-entrypoint-initdb.d/
  app:
    image: openjdk:21-jdk
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    ports:
      - "3012:3012"
    depends_on:
      - postgres
    volumes:
      - ./target/demo-0.0.1-SNAPSHOT.jar:/app/demo.jar
    working_dir: /app
    command: ["java", "-jar", "demo.jar"]
  frontend:
    image: node:20.11.1
    working_dir: /frontend
    volumes:
      - .:/frontend
    ports:
      - "3013:3013"
    command: /bin/sh -c "npm install && npm run dev"
volumes:
  postgres_data:
