INSERT INTO products (id, name, price, quantity) VALUES
  (gen_random_uuid(), 'Cat Food Salmon', 12.99, 20),
  (gen_random_uuid(), 'Cat Food Chicken', 11.49, 15),
  (gen_random_uuid(), 'Cat Food Tuna', 13.25, 18),
  (gen_random_uuid(), 'Catnip Toy Mouse', 4.99, 30),
  (gen_random_uuid(), 'Catnip Toy Ball', 3.49, 25),
  (gen_random_uuid(), 'Feather Wand', 7.99, 12),
  (gen_random_uuid(), 'Laser Pointer', 8.50, 10),
  (gen_random_uuid(), 'Scratching Post', 29.99, 5),
  (gen_random_uuid(), 'Cat Bed Plush', 24.99, 7),
  (gen_random_uuid(), 'Cat Tunnel', 15.99, 8),
  (gen_random_uuid(), 'Cat Litter 10kg', 16.99, 14),
  (gen_random_uuid(), 'Cat Litter 5kg', 9.99, 20),
  (gen_random_uuid(), 'Cat Treats Salmon', 5.99, 22),
  (gen_random_uuid(), 'Cat Treats Chicken', 5.49, 19),
  (gen_random_uuid(), 'Cat Collar Bell', 6.99, 13),
  (gen_random_uuid(), 'Cat Carrier', 34.99, 4),
  (gen_random_uuid(), 'Cat Brush', 8.99, 11),
  (gen_random_uuid(), 'Cat Shampoo', 10.99, 9),
  (gen_random_uuid(), 'Cat Water Fountain', 39.99, 3),
  (gen_random_uuid(), 'Cat Tree Deluxe', 79.99, 2),
  (gen_random_uuid(), 'Cat Harness', 14.99, 6),
  (gen_random_uuid(), 'Cat Door', 22.99, 5);
