package db

import (
	"database/sql"
)

type Product struct {
	ID       string
	Name     string
	Price    float64
	Quantity int
}

// MediaAsset represents an uploaded file tracked in the database.
type MediaAsset struct {
	ID               string
	ObjectKey        string
	OriginalFilename string
	ContentType      string
	SizeBytes        int64
	ProductId        string
	CreatedAt        string // could use time.Time, kept string for simplicity consistent with Product
}

// InsertMediaAsset inserts a media asset record.
func InsertMediaAsset(db *sql.DB, a *MediaAsset) error {
	// ID is generated by DB default gen_random_uuid() if empty
	query := `INSERT INTO media_assets (object_key, original_filename, content_type, size_bytes) VALUES ($1,$2,$3,$4) RETURNING id, created_at`
	return db.QueryRow(query, a.ObjectKey, a.OriginalFilename, a.ContentType, a.SizeBytes).Scan(&a.ID, &a.CreatedAt)
}

// ListMediaAssets returns most recent media assets limited.
func ListMediaAssets(db *sql.DB, limit int) ([]MediaAsset, error) {
	if limit <= 0 {
		limit = 50
	}
	rows, err := db.Query(`SELECT id, object_key, original_filename, content_type, size_bytes, created_at FROM media_assets ORDER BY created_at DESC LIMIT $1`, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var out []MediaAsset
	for rows.Next() {
		var m MediaAsset
		if err := rows.Scan(&m.ID, &m.ObjectKey, &m.OriginalFilename, &m.ContentType, &m.SizeBytes, &m.CreatedAt); err != nil {
			return nil, err
		}
		out = append(out, m)
	}
	return out, rows.Err()
}

func GetAllProducts(db *sql.DB, page, itemsPerPage int) ([]Product, int, error) {
	if page < 1 {
		page = 1
	}
	if itemsPerPage < 1 {
		itemsPerPage = 10
	}
	offset := (page - 1) * itemsPerPage

	// Get total count
	var total int
	err := db.QueryRow("SELECT COUNT(*) FROM products").Scan(&total)
	if err != nil {
		return nil, 0, err
	}

	// Get paginated products
	rows, err := db.Query(
		"SELECT id, name, price, quantity FROM products ORDER BY name LIMIT $1 OFFSET $2",
		itemsPerPage, offset,
	)
	if err != nil {
		return nil, 0, err
	}
	defer rows.Close()

	var products []Product
	for rows.Next() {
		var p Product
		err := rows.Scan(&p.ID, &p.Name, &p.Price, &p.Quantity)
		if err != nil {
			return nil, 0, err
		}
		products = append(products, p)
	}
	if err := rows.Err(); err != nil {
		return nil, 0, err
	}
	return products, total, nil
}
