package db

import (
	"database/sql"
	"log"
)

type Product struct {
	ID          string
	Name        string
	Price       float64
	Quantity    int
	MediaAssets []MediaAsset // related media assets (may be empty)
}

// MediaAsset represents an uploaded file tracked in the database.
type MediaAsset struct {
	ID               string
	ObjectKey        string
	OriginalFilename string
	ContentType      string
	SizeBytes        int64
	ProductId        string
	Status           string
	CreatedAt        string // could use time.Time, kept string for simplicity consistent with Product
}

// InsertMediaAsset inserts a media asset record.
func InsertMediaAsset(db *sql.DB, a *MediaAsset) error {
	// ID is generated by DB default gen_random_uuid() if empty
	query := `INSERT INTO media_assets (object_key, original_filename, content_type, size_bytes, product_id) VALUES ($1,$2,$3,$4,$5) RETURNING id, created_at`
	return db.QueryRow(query, a.ObjectKey, a.OriginalFilename, a.ContentType, a.SizeBytes, a.ProductId).Scan(&a.ID, &a.CreatedAt)
}

// ListMediaAssets returns most recent media assets limited.
func ListMediaAssets(db *sql.DB, limit int) ([]MediaAsset, error) {
	if limit <= 0 {
		limit = 50
	}
	rows, err := db.Query(`SELECT id, object_key, original_filename, content_type, size_bytes, created_at FROM media_assets ORDER BY created_at DESC LIMIT $1`, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var out []MediaAsset
	for rows.Next() {
		var m MediaAsset
		if err := rows.Scan(&m.ID, &m.ObjectKey, &m.OriginalFilename, &m.ContentType, &m.SizeBytes, &m.CreatedAt); err != nil {
			return nil, err
		}
		out = append(out, m)
	}
	return out, rows.Err()
}

func GetAllProducts(db *sql.DB, page, itemsPerPage int) ([]Product, int, error) {
	if page < 1 {
		page = 1
	}
	if itemsPerPage < 1 {
		itemsPerPage = 10
	}
	offset := (page - 1) * itemsPerPage

	// Get total count
	var total int
	err := db.QueryRow("SELECT COUNT(*) FROM products").Scan(&total)
	if err != nil {
		return nil, 0, err
	}

	// Get paginated products
	rows, err := db.Query(
		"SELECT id, name, price, quantity FROM products ORDER BY name LIMIT $1 OFFSET $2",
		itemsPerPage, offset,
	)
	if err != nil {
		return nil, 0, err
	}
	defer rows.Close()

	var products []Product
	for rows.Next() {
		var p Product
		err := rows.Scan(&p.ID, &p.Name, &p.Price, &p.Quantity)
		if err != nil {
			return nil, 0, err
		}
		products = append(products, p)
	}
	if err := rows.Err(); err != nil {
		return nil, 0, err
	}
	return products, total, nil
}

// GetAllProductsWithAssets returns paginated products including their related media assets.
// It performs a LEFT JOIN and groups the result set in memory to avoid N+1 queries.
func GetAllProductsWithAssets(db *sql.DB, page, itemsPerPage int) ([]Product, int, error) {
	if page < 1 {
		page = 1
	}
	if itemsPerPage < 1 {
		itemsPerPage = 10
	}
	offset := (page - 1) * itemsPerPage

	// Total count of products (for pagination UI)
	var total int
	if err := db.QueryRow("SELECT COUNT(*) FROM products").Scan(&total); err != nil {
		return nil, 0, err
	}

	// Joined rows; asset columns will be NULL when no assets exist for a product.
	// NOTE: We order by product name like the simple query to keep ordering consistent.
	const q = `
SELECT p.id, p.name, p.price, p.quantity,
	   ma.id, ma.object_key, ma.original_filename, ma.content_type, ma.size_bytes, ma.created_at, ma.status
  FROM products p
  LEFT JOIN media_assets ma ON ma.product_id = p.id
 ORDER BY p.name
 LIMIT $1 OFFSET $2`

	rows, err := db.Query(q, itemsPerPage, offset)
	if err != nil {
		return nil, 0, err
	}
	defer rows.Close()

	// Map for grouping while preserving first-seen order with slice.
	productIndex := make(map[string]int)
	var products []Product

	for rows.Next() {
		var (
			pid                   string
			name                  string
			price                 float64
			quantity              int
			assetID               sql.NullString
			assetObjectKey        sql.NullString
			assetOriginalFilename sql.NullString
			assetContentType      sql.NullString
			assetSizeBytes        sql.NullInt64
			assetCreatedAt        sql.NullString
			assetStatus           sql.NullString
		)
		if err := rows.Scan(
			&pid, &name, &price, &quantity,
			&assetID, &assetObjectKey, &assetOriginalFilename, &assetContentType, &assetSizeBytes, &assetCreatedAt, &assetStatus,
		); err != nil {
			return nil, 0, err
		}

		// Debug: log scanned assetID (will be empty when no asset present)
		if assetID.Valid {
			log.Printf("GetAllProductsWithAssets: product %s has assetID=%s", pid, assetID.String)
		} else {
			log.Printf("GetAllProductsWithAssets: product %s has no asset", pid)
		}


		// Ensure product exists in slice
		idx, exists := productIndex[pid]
		if !exists {
			products = append(products, Product{ID: pid, Name: name, Price: price, Quantity: quantity})
			idx = len(products) - 1
			productIndex[pid] = idx
		}

		// Append asset if present
		if assetID.Valid {
			m := MediaAsset{
				ID:               assetID.String,
				ObjectKey:        assetObjectKey.String,
				OriginalFilename: assetOriginalFilename.String,
				ContentType:      assetContentType.String,
				SizeBytes:        assetSizeBytes.Int64,
				ProductId:        pid,
				Status:           assetStatus.String,
				CreatedAt:        assetCreatedAt.String,
			}
			products[idx].MediaAssets = append(products[idx].MediaAssets, m)
		}
	}
	if err := rows.Err(); err != nil {
		return nil, 0, err
	}

	return products, total, nil
}

// UpdateMediaAssetStatusAndReturn sets the status for a media asset and returns the updated record.
func UpdateMediaAssetStatusAndReturn(db *sql.DB, id string, status string) (*MediaAsset, error) {
	var m MediaAsset
	const q = `
UPDATE media_assets
   SET status = $1
 WHERE id = $2
 RETURNING id, object_key, original_filename, content_type, size_bytes, created_at, status
`
	err := db.QueryRow(q, status, id).Scan(
		&m.ID,
		&m.ObjectKey,
		&m.OriginalFilename,
		&m.ContentType,
		&m.SizeBytes,
		&m.CreatedAt,
		&m.Status,
	)
	if err != nil {
		return nil, err
	}
	return &m, nil
}
